model:
  num_classes: 4
  pi_ge_enabled: true

data:
  train_image_dirs:
    - /kaggle/input/aquadet-unified/images/train
  val_image_dirs:
    - /kaggle/input/aquadet-unified/images/val
  enhancement_pairs_dir: /kaggle/input/uieb
  depth_supervision_dir: /kaggle/input/suim

train:
  epochs: 20
  batch_size: 8
  lr: 0.0001
  image_size: 640

loss_weights:
  cls: 1.0
  bbox: 2.0
  mask: 1.0
  depth: 0.2
